// 30 most popular sports globally with sport-specific terminology
export interface SportConfig {
  name: string;
  icon: string; // emoji
  positions: string[];
  /** What individual scoring events are called */
  scoringUnit: string;
  /** What a game/contest is called */
  matchTerm: string;
  /** What periods/halves/sets are called */
  periodTerm: string;
  /** What the playing area is called */
  venueTerm: string;
  /** Sport-specific stat categories for reports */
  keyStats: string[];
  /** Sport-specific tactical terms */
  tacticalTerms: string[];
  /** What formations/setups are called */
  formationTerm: string;
  /** Rating categories that are especially relevant */
  primaryRatingKeys: string[];
  /** Sport-specific prompt context for AI */
  aiContext: string;
}

export const SPORTS_CONFIG: Record<string, SportConfig> = {
  "Football": {
    name: "Football",
    icon: "⚽",
    positions: ["Goalkeeper", "Centre-Back", "Full-Back", "Wing-Back", "Defensive Midfielder", "Central Midfielder", "Attacking Midfielder", "Winger", "Striker", "Forward"],
    scoringUnit: "goal",
    matchTerm: "match",
    periodTerm: "half",
    venueTerm: "pitch",
    keyStats: ["Goals", "Assists", "Passes Completed", "Tackles", "Interceptions", "Shots on Target", "Dribbles", "Clean Sheets"],
    tacticalTerms: ["pressing", "counter-attack", "possession play", "high line", "low block", "overlapping runs", "through balls", "set pieces"],
    formationTerm: "Formation",
    primaryRatingKeys: ["technique", "speed", "gameIQ", "teamwork"],
    aiContext: "Use football terminology: pitch, half-time, clean sheet, assist, dribble, tackle, header, free kick, corner, penalty area.",
  },
  "Cricket": {
    name: "Cricket",
    icon: "🏏",
    positions: ["Opening Batsman", "Top-Order Batsman", "Middle-Order Batsman", "Lower-Order Batsman", "Wicketkeeper", "Fast Bowler", "Medium Pacer", "Spin Bowler", "All-Rounder", "Captain"],
    scoringUnit: "run",
    matchTerm: "match",
    periodTerm: "innings",
    venueTerm: "ground",
    keyStats: ["Runs Scored", "Batting Average", "Strike Rate", "Wickets Taken", "Economy Rate", "Catches", "Stumpings", "Run Outs"],
    tacticalTerms: ["batting order", "bowling changes", "field placement", "powerplay", "death overs", "rotation of strike", "line and length", "swing"],
    formationTerm: "Field Placement",
    primaryRatingKeys: ["technique", "focus", "composure", "gameIQ"],
    aiContext: "Use cricket terminology: crease, boundary, six, wicket, over, maiden, LBW, slip, gully, mid-on, cover, square leg. Distinguish between innings, overs, and formats (T20/ODI/Test).",
  },
  "Basketball": {
    name: "Basketball",
    icon: "🏀",
    positions: ["Point Guard", "Shooting Guard", "Small Forward", "Power Forward", "Center", "Sixth Man"],
    scoringUnit: "point",
    matchTerm: "game",
    periodTerm: "quarter",
    venueTerm: "court",
    keyStats: ["Points", "Rebounds", "Assists", "Steals", "Blocks", "Turnovers", "Field Goal %", "Free Throw %", "3-Point %"],
    tacticalTerms: ["pick and roll", "fast break", "zone defense", "man-to-man", "screen", "post-up", "transition", "half-court offense"],
    formationTerm: "Offensive Set",
    primaryRatingKeys: ["speed", "technique", "gameIQ", "teamwork"],
    aiContext: "Use basketball terminology: court, quarter, dunk, layup, three-pointer, rebound, assist, turnover, fast break, free throw, paint, key.",
  },
  "Tennis": {
    name: "Tennis",
    icon: "🎾",
    positions: ["Baseline Player", "Serve-and-Volley", "All-Court Player", "Counter-Puncher", "Aggressive Baseliner"],
    scoringUnit: "point",
    matchTerm: "match",
    periodTerm: "set",
    venueTerm: "court",
    keyStats: ["Aces", "Double Faults", "First Serve %", "Break Points Won", "Winners", "Unforced Errors", "Net Points Won"],
    tacticalTerms: ["serve and volley", "baseline rally", "drop shot", "approach shot", "topspin", "slice", "crosscourt", "down the line"],
    formationTerm: "Playing Style",
    primaryRatingKeys: ["technique", "endurance", "composure", "focus"],
    aiContext: "Use tennis terminology: set, game, deuce, advantage, break point, ace, double fault, rally, volley, lob, topspin, slice, love.",
  },
  "Badminton": {
    name: "Badminton",
    icon: "🏸",
    positions: ["Singles Player", "Doubles - Front Court", "Doubles - Rear Court", "Mixed Doubles - Net Player", "Mixed Doubles - Back Player"],
    scoringUnit: "point",
    matchTerm: "match",
    periodTerm: "game",
    venueTerm: "court",
    keyStats: ["Smash Winners", "Net Kills", "Drop Shots", "Clear Winners", "Unforced Errors", "Rally Length", "Service Points Won"],
    tacticalTerms: ["smash", "drop shot", "clear", "net play", "drive", "deception", "rotation", "lift"],
    formationTerm: "Court Position",
    primaryRatingKeys: ["speed", "technique", "endurance", "focus"],
    aiContext: "Use badminton terminology: shuttlecock, rally, smash, clear, drop shot, net kill, drive, deception, service court, love-all.",
  },
  "Table Tennis": {
    name: "Table Tennis",
    icon: "🏓",
    positions: ["Attacker", "Defender", "All-Round Player", "Pen-Hold Grip", "Shake-Hand Grip"],
    scoringUnit: "point",
    matchTerm: "match",
    periodTerm: "game",
    venueTerm: "table",
    keyStats: ["Service Aces", "Return Winners", "Topspin Winners", "Block Success", "Loop Drives", "Unforced Errors", "Rally Win %"],
    tacticalTerms: ["loop", "chop", "push", "flick", "topspin", "backspin", "sidespin", "block", "counter-drive"],
    formationTerm: "Playing Style",
    primaryRatingKeys: ["speed", "technique", "focus", "composure"],
    aiContext: "Use table tennis terminology: rally, loop, chop, push, flick, topspin, backspin, service, deuce, let, rubber, blade.",
  },
  "Volleyball": {
    name: "Volleyball",
    icon: "🏐",
    positions: ["Setter", "Outside Hitter", "Middle Blocker", "Opposite Hitter", "Libero", "Defensive Specialist"],
    scoringUnit: "point",
    matchTerm: "match",
    periodTerm: "set",
    venueTerm: "court",
    keyStats: ["Kills", "Blocks", "Aces", "Digs", "Assists", "Service Errors", "Attack %", "Reception %"],
    tacticalTerms: ["spike", "block", "dig", "set", "serve receive", "rotation", "quick attack", "pipe", "slide"],
    formationTerm: "Rotation",
    primaryRatingKeys: ["strength", "technique", "teamwork", "gameIQ"],
    aiContext: "Use volleyball terminology: set, spike, kill, block, dig, ace, rally, rotation, libero, pipe, antenna, service line.",
  },
  "Baseball": {
    name: "Baseball",
    icon: "⚾",
    positions: ["Pitcher", "Catcher", "First Baseman", "Second Baseman", "Shortstop", "Third Baseman", "Left Fielder", "Center Fielder", "Right Fielder", "Designated Hitter"],
    scoringUnit: "run",
    matchTerm: "game",
    periodTerm: "inning",
    venueTerm: "field",
    keyStats: ["Batting Average", "Home Runs", "RBIs", "Stolen Bases", "ERA", "Strikeouts", "Walks", "OBP", "Slugging %"],
    tacticalTerms: ["bunt", "steal", "hit-and-run", "sacrifice fly", "double play", "shift", "bullpen management", "lineup construction"],
    formationTerm: "Defensive Alignment",
    primaryRatingKeys: ["technique", "strength", "focus", "composure"],
    aiContext: "Use baseball terminology: inning, at-bat, strike, ball, home run, RBI, ERA, stolen base, double play, bullpen, mound, diamond.",
  },
  "Rugby": {
    name: "Rugby",
    icon: "🏉",
    positions: ["Loosehead Prop", "Hooker", "Tighthead Prop", "Lock", "Blindside Flanker", "Openside Flanker", "Number 8", "Scrum-Half", "Fly-Half", "Inside Centre", "Outside Centre", "Wing", "Full-Back"],
    scoringUnit: "point",
    matchTerm: "match",
    periodTerm: "half",
    venueTerm: "pitch",
    keyStats: ["Tries", "Conversions", "Tackles Made", "Carries", "Offloads", "Turnovers Won", "Lineout Wins", "Scrum Success"],
    tacticalTerms: ["scrum", "lineout", "ruck", "maul", "breakdown", "phase play", "crash ball", "inside pass", "kick chase"],
    formationTerm: "Formation",
    primaryRatingKeys: ["strength", "endurance", "teamwork", "composure"],
    aiContext: "Use rugby terminology: try, conversion, penalty, scrum, lineout, ruck, maul, tackle, offload, turnover, breakdown, phase.",
  },
  "Hockey": {
    name: "Hockey",
    icon: "🏑",
    positions: ["Goalkeeper", "Centre-Back", "Full-Back", "Half-Back", "Inside Forward", "Wing", "Centre Forward", "Striker"],
    scoringUnit: "goal",
    matchTerm: "match",
    periodTerm: "quarter",
    venueTerm: "pitch",
    keyStats: ["Goals", "Assists", "Penalty Corners", "Tackles", "Interceptions", "Circle Entries", "Saves", "Short Corners"],
    tacticalTerms: ["penalty corner", "short corner", "press", "through pass", "aerial ball", "reverse stick", "Indian dribble", "deflection"],
    formationTerm: "Formation",
    primaryRatingKeys: ["speed", "technique", "endurance", "teamwork"],
    aiContext: "Use field hockey terminology: circle, penalty corner, short corner, reverse stick, aerial, push, slap, drag flick, D-area.",
  },
  "Ice Hockey": {
    name: "Ice Hockey",
    icon: "🏒",
    positions: ["Goaltender", "Left Defenseman", "Right Defenseman", "Left Wing", "Center", "Right Wing"],
    scoringUnit: "goal",
    matchTerm: "game",
    periodTerm: "period",
    venueTerm: "rink",
    keyStats: ["Goals", "Assists", "Plus/Minus", "Shots on Goal", "Save %", "Faceoff Wins", "Penalty Minutes", "Time on Ice"],
    tacticalTerms: ["power play", "penalty kill", "breakout", "forecheck", "backcheck", "dump and chase", "one-timer", "wraparound"],
    formationTerm: "System",
    primaryRatingKeys: ["speed", "strength", "technique", "gameIQ"],
    aiContext: "Use ice hockey terminology: puck, rink, period, power play, penalty kill, faceoff, breakaway, slapshot, wrist shot, crease.",
  },
  "Golf": {
    name: "Golf",
    icon: "⛳",
    positions: ["Driver Specialist", "Iron Player", "Short Game Specialist", "Putter"],
    scoringUnit: "stroke",
    matchTerm: "round",
    periodTerm: "round",
    venueTerm: "course",
    keyStats: ["Scoring Average", "Fairways Hit %", "Greens in Regulation", "Putts per Round", "Driving Distance", "Scrambling %", "Sand Save %"],
    tacticalTerms: ["tee shot", "approach", "chip", "pitch", "putt", "fade", "draw", "course management", "club selection"],
    formationTerm: "Game Plan",
    primaryRatingKeys: ["technique", "composure", "focus", "discipline"],
    aiContext: "Use golf terminology: birdie, par, bogey, eagle, fairway, green, bunker, rough, tee box, drive, iron, wedge, putt, handicap.",
  },
  "Swimming": {
    name: "Swimming",
    icon: "🏊",
    positions: ["Freestyle Specialist", "Backstroke Specialist", "Breaststroke Specialist", "Butterfly Specialist", "IM Specialist", "Distance Swimmer", "Sprint Swimmer", "Relay Swimmer"],
    scoringUnit: "time",
    matchTerm: "race",
    periodTerm: "lap",
    venueTerm: "pool",
    keyStats: ["Personal Best", "Split Times", "Stroke Rate", "Turns Efficiency", "Underwater Phase", "Race Pace", "DPS (Distance Per Stroke)"],
    tacticalTerms: ["pacing", "negative split", "underwater dolphin kick", "streamline", "flip turn", "breakout", "catch phase", "pull"],
    formationTerm: "Race Strategy",
    primaryRatingKeys: ["endurance", "technique", "speed", "discipline"],
    aiContext: "Use swimming terminology: lane, heat, final, split, PB, stroke count, DPS, flip turn, streamline, breakout, catch, pull, kick.",
  },
  "Athletics": {
    name: "Athletics",
    icon: "🏃",
    positions: ["Sprinter", "Middle Distance", "Long Distance", "Hurdler", "Jumper", "Thrower", "Multi-Event Athlete", "Race Walker", "Marathon Runner"],
    scoringUnit: "result",
    matchTerm: "competition",
    periodTerm: "event",
    venueTerm: "track/field",
    keyStats: ["Personal Best", "Season Best", "Reaction Time", "Split Times", "Stride Length", "Block Start Time", "Peak Velocity"],
    tacticalTerms: ["block start", "drive phase", "stride frequency", "kick", "pace judgment", "approach run", "release angle", "follow through"],
    formationTerm: "Race Plan",
    primaryRatingKeys: ["speed", "endurance", "technique", "discipline"],
    aiContext: "Use athletics terminology: PB, SB, heat, final, lane, blocks, reaction time, split, kick, form, drive phase, clearance height, throwing mark.",
  },
  "Boxing": {
    name: "Boxing",
    icon: "🥊",
    positions: ["Orthodox Fighter", "Southpaw", "Switch Hitter", "Out-Fighter", "In-Fighter", "Brawler", "Counter-Puncher"],
    scoringUnit: "point",
    matchTerm: "bout",
    periodTerm: "round",
    venueTerm: "ring",
    keyStats: ["Punches Landed", "Punch Accuracy", "Jab %", "Power Punch %", "Body Shots", "Defense Rate", "Knockdowns"],
    tacticalTerms: ["jab", "cross", "hook", "uppercut", "combination", "footwork", "head movement", "clinch", "counter"],
    formationTerm: "Fight Plan",
    primaryRatingKeys: ["speed", "strength", "composure", "endurance"],
    aiContext: "Use boxing terminology: round, bout, ring, jab, cross, hook, uppercut, combination, clinch, knockdown, KO, TKO, split decision.",
  },
  "MMA": {
    name: "Mixed Martial Arts",
    icon: "🥋",
    positions: ["Striker", "Grappler", "Wrestler", "BJJ Specialist", "Well-Rounded Fighter"],
    scoringUnit: "point",
    matchTerm: "bout",
    periodTerm: "round",
    venueTerm: "cage/octagon",
    keyStats: ["Significant Strikes", "Takedowns", "Submissions Attempted", "Control Time", "Strike Accuracy", "Takedown Defense %"],
    tacticalTerms: ["ground-and-pound", "clinch work", "takedown", "sprawl", "submission", "guard", "mount", "back control", "cage control"],
    formationTerm: "Game Plan",
    primaryRatingKeys: ["strength", "endurance", "composure", "technique"],
    aiContext: "Use MMA terminology: octagon, cage, round, submission, takedown, ground-and-pound, clinch, sprawl, guard, mount, KO, TKO, decision.",
  },
  "Gymnastics": {
    name: "Gymnastics",
    icon: "🤸",
    positions: ["Floor Specialist", "Vault Specialist", "Bars Specialist", "Beam Specialist", "All-Around", "Rings Specialist", "Pommel Horse Specialist"],
    scoringUnit: "score",
    matchTerm: "competition",
    periodTerm: "rotation",
    venueTerm: "arena",
    keyStats: ["Difficulty Score", "Execution Score", "All-Around Total", "Apparatus Final Score", "Deductions", "Landing Score"],
    tacticalTerms: ["routine", "dismount", "connection bonus", "difficulty value", "execution deduction", "stick landing", "salto", "pike"],
    formationTerm: "Routine",
    primaryRatingKeys: ["technique", "strength", "composure", "discipline"],
    aiContext: "Use gymnastics terminology: routine, apparatus, vault, bars, beam, floor, dismount, D-score, E-score, deduction, stick landing, salto.",
  },
  "Cycling": {
    name: "Cycling",
    icon: "🚴",
    positions: ["Sprinter", "Climber", "Time Trialist", "All-Rounder", "Domestique", "Lead-Out", "GC Contender"],
    scoringUnit: "time/point",
    matchTerm: "race/stage",
    periodTerm: "stage",
    venueTerm: "course/velodrome",
    keyStats: ["Average Speed", "Power Output (Watts)", "Cadence", "Heart Rate Zones", "Climbing Rate", "Sprint Speed", "Time Gap"],
    tacticalTerms: ["peloton", "breakaway", "drafting", "leadout", "attack", "sprint finish", "time trial", "mountain stage"],
    formationTerm: "Race Tactics",
    primaryRatingKeys: ["endurance", "speed", "discipline", "composure"],
    aiContext: "Use cycling terminology: peloton, breakaway, domestique, GC, sprint, climb, TT, watts, cadence, draft, leadout, stage.",
  },
  "Handball": {
    name: "Handball",
    icon: "🤾",
    positions: ["Goalkeeper", "Left Wing", "Right Wing", "Left Back", "Centre Back", "Right Back", "Pivot/Line Player"],
    scoringUnit: "goal",
    matchTerm: "match",
    periodTerm: "half",
    venueTerm: "court",
    keyStats: ["Goals", "Assists", "Saves", "Turnovers", "Steals", "Shooting %", "Fast Break Goals"],
    tacticalTerms: ["fast break", "pivot play", "wing attack", "6-0 defense", "5-1 defense", "7-meter throw", "suspension", "backcourt shot"],
    formationTerm: "Defensive Formation",
    primaryRatingKeys: ["strength", "speed", "technique", "teamwork"],
    aiContext: "Use handball terminology: court, goal area, 6-meter line, 7-meter throw, fast break, pivot, wing, backcourt, suspension.",
  },
  "Wrestling": {
    name: "Wrestling",
    icon: "🤼",
    positions: ["Freestyle", "Greco-Roman", "Folkstyle", "Lightweight", "Middleweight", "Heavyweight"],
    scoringUnit: "point",
    matchTerm: "bout",
    periodTerm: "period",
    venueTerm: "mat",
    keyStats: ["Takedowns", "Pins", "Technical Points", "Escapes", "Reversals", "Near Falls", "Riding Time"],
    tacticalTerms: ["takedown", "pin", "escape", "reversal", "near fall", "riding time", "gut wrench", "single leg", "double leg"],
    formationTerm: "Wrestling Style",
    primaryRatingKeys: ["strength", "endurance", "technique", "composure"],
    aiContext: "Use wrestling terminology: mat, bout, period, takedown, pin/fall, escape, reversal, near fall, riding time, neutral position.",
  },
  "Fencing": {
    name: "Fencing",
    icon: "🤺",
    positions: ["Épée Fencer", "Foil Fencer", "Sabre Fencer"],
    scoringUnit: "touch",
    matchTerm: "bout",
    periodTerm: "period",
    venueTerm: "piste",
    keyStats: ["Touches Scored", "Attack Success %", "Parry-Riposte %", "Counter-Attack %", "Right of Way Won"],
    tacticalTerms: ["attack", "parry", "riposte", "counter-attack", "feint", "lunge", "flèche", "beat attack", "disengage"],
    formationTerm: "Tactical Approach",
    primaryRatingKeys: ["speed", "focus", "composure", "technique"],
    aiContext: "Use fencing terminology: piste, bout, touch, attack, parry, riposte, counter-attack, feint, lunge, en garde, right of way, priority.",
  },
  "Squash": {
    name: "Squash",
    icon: "🎯",
    positions: ["Attacker", "Retriever", "All-Court Player", "Power Player"],
    scoringUnit: "point",
    matchTerm: "match",
    periodTerm: "game",
    venueTerm: "court",
    keyStats: ["Winners", "Errors", "Rally Length", "Tin Shots", "Volleys", "Drops", "Boasts"],
    tacticalTerms: ["boast", "drop", "lob", "volley", "cross-court", "straight drive", "nick", "T-position", "ghosting"],
    formationTerm: "Court Strategy",
    primaryRatingKeys: ["endurance", "speed", "technique", "focus"],
    aiContext: "Use squash terminology: T-position, tin, nick, boast, drop, lob, cross-court, straight drive, let, stroke, rally, service box.",
  },
  "Rowing": {
    name: "Rowing",
    icon: "🚣",
    positions: ["Single Sculler", "Pair", "Coxless Four", "Eight", "Coxswain", "Stroke Seat", "Bow Seat"],
    scoringUnit: "time",
    matchTerm: "race",
    periodTerm: "race",
    venueTerm: "course/lake",
    keyStats: ["Split Time (500m)", "Stroke Rate", "Power Output", "Race Time", "Start Sprint", "Body of Race", "Sprint Finish"],
    tacticalTerms: ["catch", "drive", "finish", "recovery", "power ten", "rating", "settle", "push", "sprint"],
    formationTerm: "Race Plan",
    primaryRatingKeys: ["endurance", "strength", "teamwork", "discipline"],
    aiContext: "Use rowing terminology: stroke rate, split, catch, drive, finish, recovery, power ten, settle, bow, stern, port, starboard.",
  },
  "Surfing": {
    name: "Surfing",
    icon: "🏄",
    positions: ["Shortboarder", "Longboarder", "Big Wave Surfer", "Aerial Specialist"],
    scoringUnit: "score",
    matchTerm: "heat",
    periodTerm: "heat",
    venueTerm: "break",
    keyStats: ["Wave Score", "Best Wave", "Total Score", "Priority Calls", "Wave Count", "Completion Rate"],
    tacticalTerms: ["bottom turn", "cutback", "aerial", "tube ride", "carve", "snap", "floater", "priority", "wave selection"],
    formationTerm: "Heat Strategy",
    primaryRatingKeys: ["technique", "composure", "speed", "focus"],
    aiContext: "Use surfing terminology: heat, wave, lineup, priority, tube, barrel, cutback, aerial, snap, bottom turn, carve, wipeout.",
  },
  "Weightlifting": {
    name: "Weightlifting",
    icon: "🏋️",
    positions: ["Snatch Specialist", "Clean & Jerk Specialist", "All-Around Lifter"],
    scoringUnit: "kg",
    matchTerm: "competition",
    periodTerm: "attempt",
    venueTerm: "platform",
    keyStats: ["Snatch Best", "Clean & Jerk Best", "Total", "Sinclair Score", "Body Weight Category", "Attempt Success Rate"],
    tacticalTerms: ["snatch", "clean", "jerk", "pull", "catch", "squat", "lockout", "opener", "attempt selection"],
    formationTerm: "Attempt Strategy",
    primaryRatingKeys: ["strength", "technique", "discipline", "composure"],
    aiContext: "Use weightlifting terminology: platform, snatch, clean & jerk, total, attempt, opener, pull, catch, squat, lockout, body weight class.",
  },
  "Archery": {
    name: "Archery",
    icon: "🏹",
    positions: ["Recurve Archer", "Compound Archer", "Barebow Archer"],
    scoringUnit: "point",
    matchTerm: "match",
    periodTerm: "end",
    venueTerm: "range",
    keyStats: ["Average Score", "X-Count", "10s Count", "End Average", "Grouping Size", "Wind Adjustment Accuracy"],
    tacticalTerms: ["anchor point", "release", "follow-through", "aiming", "grouping", "wind reading", "shot sequence", "clicker"],
    formationTerm: "Shot Process",
    primaryRatingKeys: ["focus", "composure", "discipline", "technique"],
    aiContext: "Use archery terminology: end, arrow, target, X-ring, 10-ring, anchor, release, follow-through, grouping, clicker, bow hand.",
  },
  "Martial Arts": {
    name: "Martial Arts",
    icon: "🥋",
    positions: ["Karate", "Taekwondo", "Judo", "Kung Fu", "Kendo", "Aikido"],
    scoringUnit: "point",
    matchTerm: "bout/match",
    periodTerm: "round",
    venueTerm: "dojo/mat",
    keyStats: ["Points Scored", "Techniques Landed", "Kata Score", "Ippon Count", "Waza-ari Count", "Defense Rate"],
    tacticalTerms: ["kata", "kumite", "ippon", "waza-ari", "kiai", "stance", "block", "counter", "sweep"],
    formationTerm: "Fighting Strategy",
    primaryRatingKeys: ["technique", "discipline", "composure", "speed"],
    aiContext: "Use martial arts terminology: dojo, sensei, kata, kumite, ippon, waza-ari, belt, dan, kiai, stance, block, sweep.",
  },
  "Sailing": {
    name: "Sailing",
    icon: "⛵",
    positions: ["Skipper/Helm", "Crew/Trimmer", "Bowman", "Tactician", "Navigator"],
    scoringUnit: "place",
    matchTerm: "race",
    periodTerm: "leg",
    venueTerm: "course/water",
    keyStats: ["Finish Position", "Starts Won", "Tacking Efficiency", "Mark Rounding", "Wind Shifts Read", "Boat Speed"],
    tacticalTerms: ["tacking", "jibing", "windward", "leeward", "port/starboard", "mark rounding", "start line", "protest"],
    formationTerm: "Race Strategy",
    primaryRatingKeys: ["gameIQ", "teamwork", "composure", "focus"],
    aiContext: "Use sailing terminology: helm, tack, jibe, windward, leeward, port, starboard, mark, buoy, start line, protest, spinnaker.",
  },
  "Skateboarding": {
    name: "Skateboarding",
    icon: "🛹",
    positions: ["Street Skater", "Park Skater", "Vert Skater", "Bowl Skater"],
    scoringUnit: "score",
    matchTerm: "run/jam",
    periodTerm: "run",
    venueTerm: "park/street course",
    keyStats: ["Best Trick Score", "Run Score", "Consistency %", "Trick Difficulty", "Trick Variety", "Landing Rate"],
    tacticalTerms: ["kickflip", "ollie", "grind", "slide", "aerial", "transition", "line", "combo", "landing"],
    formationTerm: "Run Plan",
    primaryRatingKeys: ["technique", "composure", "speed", "focus"],
    aiContext: "Use skateboarding terminology: trick, kickflip, ollie, grind, slide, rail, ramp, halfpipe, run, line, combo, landing, bail.",
  },
};

export const SPORT_NAMES = Object.keys(SPORTS_CONFIG);

export function getSportConfig(sportName: string): SportConfig | undefined {
  return SPORTS_CONFIG[sportName];
}

export function getSportPositions(sportName: string): string[] {
  return SPORTS_CONFIG[sportName]?.positions || [];
}

export function getSportAIContext(sportName: string): string {
  return SPORTS_CONFIG[sportName]?.aiContext || "";
}
