import { MessageCircle, Mail, Share2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { toast } from "sonner";

interface ShareButtonsProps {
  shareLink: string;
  type: "player" | "match" | "video";
  playerName?: string;
  academyName?: string;
  matchTitle?: string;
  matchDate?: string;
  matchResult?: string;
  sport?: string;
  coachName?: string;
  reportPreview?: string;
}

const ShareButtons = ({
  shareLink,
  type,
  playerName,
  academyName,
  matchTitle,
  matchDate,
  matchResult,
  sport,
  coachName,
  reportPreview,
}: ShareButtonsProps) => {
  const getWhatsAppMessage = () => {
    if (type === "player") {
      return `Hi! Here is ${playerName}'s monthly progress report from ${academyName || "our academy"}. Tap the link to view:\n${shareLink}\n\nGenerated by SportVault — sportvault.in`;
    }
    if (type === "match") {
      return `${academyName || "Academy"} — Match Report\n${matchTitle || "Match"} · ${matchDate || ""} · ${matchResult || ""}\n\nView the full analysis: ${shareLink}\n\nPowered by SportVault`;
    }
    return `Match Analysis Ready 🎯\n${matchTitle || "Match"} — ${sport || ""}\n\nView full tactical breakdown: ${shareLink}\n\nSportVault — sportvault.in`;
  };

  const getEmailSubject = () => {
    if (type === "player") return `${playerName} — Monthly Progress Report from ${academyName || "Academy"}`;
    if (type === "match") return `Match Report: ${matchTitle || "Match"} — ${academyName || "Academy"}`;
    return `Match Analysis: ${matchTitle || "Match"} — ${sport || ""}`;
  };

  const getEmailBody = () => {
    if (type === "player") {
      const preview = reportPreview ? `\n\n${reportPreview.slice(0, 200)}...\n` : "";
      return `Dear Parent,\n\nPlease find ${playerName}'s monthly progress report from ${academyName || "our academy"} below.\n\nView Report: ${shareLink}${preview}\n\nBest regards,\n${coachName || "Coach"}\n${academyName || ""}\n\n---\nPowered by SportVault — sportvault.in`;
    }
    return `View the full report here: ${shareLink}\n\n---\nPowered by SportVault — sportvault.in`;
  };

  const handleWhatsApp = () => {
    const msg = encodeURIComponent(getWhatsAppMessage());
    window.open(`https://wa.me/?text=${msg}`, "_blank");
  };

  const handleEmail = () => {
    const subject = encodeURIComponent(getEmailSubject());
    const body = encodeURIComponent(getEmailBody());
    window.open(`https://mail.google.com/mail/?view=cm&fs=1&su=${subject}&body=${body}`, "_blank");
  };

  const handleCopyLink = () => {
    navigator.clipboard.writeText(shareLink);
    toast.success("Share link copied!");
  };

  return (
    <div className="flex items-center gap-2">
      <Button size="sm" onClick={handleWhatsApp} className="bg-[#25D366] hover:bg-[#20BD5A] text-white">
        <MessageCircle className="h-3.5 w-3.5 mr-1" /> WhatsApp
      </Button>
      <Button size="sm" variant="outline" onClick={handleEmail}>
        <Mail className="h-3.5 w-3.5 mr-1" /> Email
      </Button>
      <Button size="sm" variant="ghost" onClick={handleCopyLink}>
        <Share2 className="h-3.5 w-3.5 mr-1" /> Copy Link
      </Button>
    </div>
  );
};

export default ShareButtons;
